version: '3.8'

services:
  {{.ProjectName}}:
    build:
      context: .
      dockerfile: Dockerfile
    image: {{.ProjectName}}:latest
    container_name: {{.ProjectName}}
    environment:
      - {{.PROJECTNAME}}_CONFIG=/config/config.yaml
    volumes:
      - ./config:/config:ro
      - ./data:/data
    # Uncomment if your CLI runs as a service
    # restart: unless-stopped
    # ports:
    #   - "8080:8080"
    
  # Example database service
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: {{.ProjectName}}-db
  #   environment:
  #     POSTGRES_USER: {{.ProjectName}}
  #     POSTGRES_PASSWORD: changeme
  #     POSTGRES_DB: {{.ProjectName}}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: