# Repository Settings for Probot Settings App
# Automatically manages labels, branch protection, and other repository settings
# Install: https://github.com/apps/settings

repository:
  name: go-cli-template
  description: A comprehensive template for building Go CLI applications with Cobra, modern tooling, and AI integration
  homepage: https://github.com/MOlechowski/go-cli-template
  topics: go, cli, template, cobra, golang, ai-integration, claude-code
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Label Configuration
labels:
  # Type Labels
  - name: "type:bug"
    color: "d73a4a"
    description: "Something isn't working correctly"
  - name: "type:feature"
    color: "a2eeef"
    description: "New functionality or enhancement"
  - name: "type:docs"
    color: "0075ca"
    description: "Documentation improvements or additions"
  - name: "type:deps"
    color: "0366d6"
    description: "Dependency updates and management"
  - name: "type:refactor"
    color: "d4c5f9"
    description: "Code refactoring without functional changes"
  - name: "type:test"
    color: "c7def8"
    description: "Testing improvements or additions"

  # Priority Labels
  - name: "priority:critical"
    color: "b60205"
    description: "Critical issue requiring immediate attention"
  - name: "priority:high"
    color: "d93f0b"
    description: "High priority, should be addressed soon"
  - name: "priority:medium"
    color: "fbca04"
    description: "Medium priority, normal timeline"
  - name: "priority:low"
    color: "0e8a16"
    description: "Low priority, can be addressed later"

  # Status Labels
  - name: "status:triage"
    color: "ededed"
    description: "Needs initial review and categorization"
  - name: "status:accepted"
    color: "c2e0c6"
    description: "Issue/PR has been approved for work"
  - name: "status:in-progress"
    color: "ffcc00"
    description: "Currently being worked on"
  - name: "status:blocked"
    color: "d93f0b"
    description: "Blocked by external dependency or issue"
  - name: "status:waiting-feedback"
    color: "f9d0c4"
    description: "Waiting for feedback from contributor or maintainer"

  # Area Labels (Go CLI Project Specific)
  - name: "area:cli"
    color: "84b6eb"
    description: "Command-line interface and command structure"
  - name: "area:config"
    color: "c5def5"
    description: "Configuration management (Viper, YAML, etc.)"
  - name: "area:logging"
    color: "bfd4f2"
    description: "Logging system and output formatting"
  - name: "area:error-handling"
    color: "d4c5f9"
    description: "Error handling and user messaging"
  - name: "area:testing"
    color: "c7def8"
    description: "Test infrastructure and test cases"
  - name: "area:build"
    color: "f9c513"
    description: "Build system, CI/CD, and release process"
  - name: "area:docs"
    color: "006b75"
    description: "Documentation and examples"

  # Special Labels
  - name: "good-first-issue"
    color: "7057ff"
    description: "Good for newcomers to the project"
  - name: "help-wanted"
    color: "008672"
    description: "Looking for community contributions"
  - name: "breaking-change"
    color: "d93f0b"
    description: "Introduces breaking changes to the API"
  - name: "needs-discussion"
    color: "d876e3"
    description: "Requires community or maintainer discussion"
  
  # AI/Claude Integration Labels
  - name: "claude-ai"
    color: "ff6b35"
    description: "Issues related to Claude Code AI integration"
  - name: "ai-generated"
    color: "ff9500"
    description: "Code or content generated by AI assistant"
  - name: "ai-reviewed"
    color: "ff7518"
    description: "Reviewed or analyzed by AI assistant"

  # Template-Specific Labels
  - name: "template-enhancement"
    color: "1d76db"
    description: "Improvements to the template structure or features"
  - name: "example-code"
    color: "5319e7"
    description: "Example implementations or sample code"
  - name: "template-docs"
    color: "0e8a16"
    description: "Template documentation and usage guides"

# Branch Protection Rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Lint"
          - "Test (ubuntu-latest)"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false