version: "2"

run:
  timeout: 10m
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 3

linters:
  enable:
    # Core quality linters (2025 recommendations)
    - errcheck      # Critical error handling
    - govet         # Built-in Go analysis
    - ineffassign   # Performance optimization
    - unused        # Dead code detection
    - misspell      # Documentation quality
    - staticcheck   # Comprehensive static analysis
    
    # Style and best practices
    - revive        # Enhanced style checking
    
    # Security and safety
    - gosec         # Security vulnerabilities
    - bodyclose     # Resource leak prevention
    - noctx         # Context propagation
    
    # Performance and maintainability
    - goconst       # Constant extraction opportunities
    - unconvert     # Unnecessary type conversions
    - unparam       # Unused parameters
    - whitespace    # Whitespace issues
    
    # Code complexity management
    - gocyclo       # Cyclomatic complexity
    - nakedret      # Naked returns in long functions
    - gocritic      # Advanced diagnostics

  settings:
    misspell:
      locale: US
    goconst:
      min-len: 2
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Often too noisy for existing code
    revive:
      rules:
        - name: exported
          severity: warning
        - name: var-naming
          severity: warning
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf

  exclusions:
    paths:
      - ".*_test\\.go$"    # Test files get different rules
    warn-unused: true

formatters:
  enable:
    - gofmt         # Code formatting
    - goimports     # Import organization
  settings:
    gofmt:
      simplify: true