version: "2"

linters:
  default: standard
  enable:
    - misspell
    - govet
    - errcheck
    - ineffassign
    - revive
    - bodyclose
    - dogsled
    - dupl
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - nakedret
    - noctx
    - unconvert
    - unparam
    - whitespace
  disable:
    - unused
  settings:
    misspell:
      locale: US
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    revive:
      rules:
        - name: exported
          severity: warning
        - name: var-naming
          severity: warning
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - dupl