name: Claude Code

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, synchronize, reopened]
  pull_request_review_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  claude:
    if: |
      contains(github.event.issue.body || github.event.comment.body || github.event.pull_request.body, '@claude') ||
      contains(github.event.issue.body || github.event.comment.body || github.event.pull_request.body, '@claude-code')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-iterations: 5
          model: claude-3-5-sonnet-20241022
          timeout-minutes: 25