name: Go Report Card

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  refresh:
    name: Refresh Go Report Card
    runs-on: ubuntu-latest
    steps:
      - uses: creekorful/goreportcard-action@v1.0