name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  GO_VERSION: '1.24'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ${{ vars.UBUNTU_RUNNER || 'ubuntu-latest' }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      
      - name: Cache Task binary
        uses: actions/cache@v4
        with:
          path: ~/.local/share/task
          key: ${{ runner.os }}-task-${{ hashFiles('Taskfile.yml') }}
      
      - name: Install Task
        if: steps.download-artifacts.outcome == 'failure'
        uses: arduino/setup-task@v2
        with:
          version: 3.x
      
      - name: Download CI artifacts
        id: download-artifacts
        uses: actions/download-artifact@v5
        with:
          name: binaries-${{ github.run_id }}
          path: dist/
        continue-on-error: true
      
      - name: Run tests
        if: steps.download-artifacts.outcome == 'failure'
        run: task test:short
      
      - name: Build release binaries
        if: steps.download-artifacts.outcome == 'failure'
        env:
          CGO_ENABLED: 0
          GOMAXPROCS: 4
        run: task release
      
      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-version-file: true
          output-file: false
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.clean_changelog }}
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/checksums.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}